/**
 * OData Service
 * This OData service is located at http://localhost
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */import { OdataErrorMain } from './odataErrorMain';


export interface OdataError { 
    error: OdataErrorMain;
}