/**
 * OData Service
 * This OData service is located at http://localhost
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */import { OdataErrorDetail } from './odataErrorDetail';


export interface OdataErrorMain { 
    code: string;
    message: string;
    target?: string;
    details?: Array<OdataErrorDetail>;
    /**
     * The structure of this object is service-specific
     */
    innererror?: any;
}