/**
 * OData Service
 * This OData service is located at http://localhost
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Ticket { 
    id?: number;
    key?: string;
    summary?: string;
    description?: string;
    priority?: number;
    resolution?: number;
    asigneeId?: number;
    reporterId?: number;
    reportedDate?: string;
}